/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace SWIG.BWAPI {

public enum EventType_Enum {
  MatchStart,
  MatchEnd,
  MatchFrame,
  MenuFrame,
  SendText,
  ReceiveText,
  PlayerLeft,
  NukeDetect,
  UnitDiscover,
  UnitEvade,
  UnitShow,
  UnitHide,
  UnitCreate,
  UnitDestroy,
  UnitMorph,
  UnitRenegade,
  SaveGame,
  UnitComplete,
  PlayerDropped,
  None
}

}
