//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace SWIG.BWAPIC {
 
	// defaults
	using System; 
	using System.Runtime.InteropServices; 
	// BWAPI
	using BWAPI;

public partial class BulletData : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal BulletData(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(BulletData obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~BulletData() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          bwapiclientPINVOKE.delete_BulletData(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  
public override int GetHashCode()
{
   return this.swigCPtr.Handle.GetHashCode();
}

public override bool Equals(object obj)
{
    bool equal = false;
    if (obj is BulletData)
      equal = (((BulletData)obj).swigCPtr.Handle == this.swigCPtr.Handle);
    return equal;
}
  
public bool Equals(BulletData obj) 
{
    if (obj == null) return false;
    return (obj.swigCPtr.Handle == this.swigCPtr.Handle);
}

public static bool operator ==(BulletData obj1, BulletData obj2)
{
    if (object.ReferenceEquals(obj1, obj2)) return true;
    if (object.ReferenceEquals(obj1, null)) return false;
    if (object.ReferenceEquals(obj2, null)) return false;
   
    return obj1.Equals(obj2);
}

public static bool operator !=(BulletData obj1, BulletData obj2)
{
    if (object.ReferenceEquals(obj1, obj2)) return false;
    if (object.ReferenceEquals(obj1, null)) return true;
    if (object.ReferenceEquals(obj2, null)) return true;

    return !obj1.Equals(obj2);
}




  public int id {
    set {
      bwapiclientPINVOKE.BulletData_id_set(swigCPtr, value);
    } 
    get {
      int ret = bwapiclientPINVOKE.BulletData_id_get(swigCPtr);
      return ret;
    } 
  }

  public int player {
    set {
      bwapiclientPINVOKE.BulletData_player_set(swigCPtr, value);
    } 
    get {
      int ret = bwapiclientPINVOKE.BulletData_player_get(swigCPtr);
      return ret;
    } 
  }

  public int type {
    set {
      bwapiclientPINVOKE.BulletData_type_set(swigCPtr, value);
    } 
    get {
      int ret = bwapiclientPINVOKE.BulletData_type_get(swigCPtr);
      return ret;
    } 
  }

  public int source {
    set {
      bwapiclientPINVOKE.BulletData_source_set(swigCPtr, value);
    } 
    get {
      int ret = bwapiclientPINVOKE.BulletData_source_get(swigCPtr);
      return ret;
    } 
  }

  public int positionX {
    set {
      bwapiclientPINVOKE.BulletData_positionX_set(swigCPtr, value);
    } 
    get {
      int ret = bwapiclientPINVOKE.BulletData_positionX_get(swigCPtr);
      return ret;
    } 
  }

  public int positionY {
    set {
      bwapiclientPINVOKE.BulletData_positionY_set(swigCPtr, value);
    } 
    get {
      int ret = bwapiclientPINVOKE.BulletData_positionY_get(swigCPtr);
      return ret;
    } 
  }

  public double angle {
    set {
      bwapiclientPINVOKE.BulletData_angle_set(swigCPtr, value);
    } 
    get {
      double ret = bwapiclientPINVOKE.BulletData_angle_get(swigCPtr);
      return ret;
    } 
  }

  public double velocityX {
    set {
      bwapiclientPINVOKE.BulletData_velocityX_set(swigCPtr, value);
    } 
    get {
      double ret = bwapiclientPINVOKE.BulletData_velocityX_get(swigCPtr);
      return ret;
    } 
  }

  public double velocityY {
    set {
      bwapiclientPINVOKE.BulletData_velocityY_set(swigCPtr, value);
    } 
    get {
      double ret = bwapiclientPINVOKE.BulletData_velocityY_get(swigCPtr);
      return ret;
    } 
  }

  public int target {
    set {
      bwapiclientPINVOKE.BulletData_target_set(swigCPtr, value);
    } 
    get {
      int ret = bwapiclientPINVOKE.BulletData_target_get(swigCPtr);
      return ret;
    } 
  }

  public int targetPositionX {
    set {
      bwapiclientPINVOKE.BulletData_targetPositionX_set(swigCPtr, value);
    } 
    get {
      int ret = bwapiclientPINVOKE.BulletData_targetPositionX_get(swigCPtr);
      return ret;
    } 
  }

  public int targetPositionY {
    set {
      bwapiclientPINVOKE.BulletData_targetPositionY_set(swigCPtr, value);
    } 
    get {
      int ret = bwapiclientPINVOKE.BulletData_targetPositionY_get(swigCPtr);
      return ret;
    } 
  }

  public int removeTimer {
    set {
      bwapiclientPINVOKE.BulletData_removeTimer_set(swigCPtr, value);
    } 
    get {
      int ret = bwapiclientPINVOKE.BulletData_removeTimer_get(swigCPtr);
      return ret;
    } 
  }

  public bool exists {
    set {
      bwapiclientPINVOKE.BulletData_exists_set(swigCPtr, value);
    } 
    get {
      bool ret = bwapiclientPINVOKE.BulletData_exists_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_bool isVisible {
    set {
      bwapiclientPINVOKE.BulletData_isVisible_set(swigCPtr, SWIGTYPE_p_bool.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = bwapiclientPINVOKE.BulletData_isVisible_get(swigCPtr);
      SWIGTYPE_p_bool ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_bool(cPtr, false);
      return ret;
    } 
  }

  public BulletData() : this(bwapiclientPINVOKE.new_BulletData(), true) {
  }

}

}
