//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace SWIG.BWAPIC {
 
	// defaults
	using System; 
	using System.Runtime.InteropServices; 
	// BWAPI
	using BWAPI;

public partial class BWAPIC_UnitCommand : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal BWAPIC_UnitCommand(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(BWAPIC_UnitCommand obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~BWAPIC_UnitCommand() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          bwapiclientPINVOKE.delete_BWAPIC_UnitCommand(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  
public override int GetHashCode()
{
   return this.swigCPtr.Handle.GetHashCode();
}

public override bool Equals(object obj)
{
    bool equal = false;
    if (obj is BWAPIC_UnitCommand)
      equal = (((BWAPIC_UnitCommand)obj).swigCPtr.Handle == this.swigCPtr.Handle);
    return equal;
}
  
public bool Equals(BWAPIC_UnitCommand obj) 
{
    if (obj == null) return false;
    return (obj.swigCPtr.Handle == this.swigCPtr.Handle);
}

public static bool operator ==(BWAPIC_UnitCommand obj1, BWAPIC_UnitCommand obj2)
{
    if (object.ReferenceEquals(obj1, obj2)) return true;
    if (object.ReferenceEquals(obj1, null)) return false;
    if (object.ReferenceEquals(obj2, null)) return false;
   
    return obj1.Equals(obj2);
}

public static bool operator !=(BWAPIC_UnitCommand obj1, BWAPIC_UnitCommand obj2)
{
    if (object.ReferenceEquals(obj1, obj2)) return false;
    if (object.ReferenceEquals(obj1, null)) return true;
    if (object.ReferenceEquals(obj2, null)) return true;

    return !obj1.Equals(obj2);
}




  public UnitCommandType type {
    set {
      bwapiclientPINVOKE.BWAPIC_UnitCommand_type_set(swigCPtr, UnitCommandType.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = bwapiclientPINVOKE.BWAPIC_UnitCommand_type_get(swigCPtr);
      UnitCommandType ret = (cPtr == global::System.IntPtr.Zero) ? null : new UnitCommandType(cPtr, false);
      return ret;
    } 
  }

  public int unitIndex {
    set {
      bwapiclientPINVOKE.BWAPIC_UnitCommand_unitIndex_set(swigCPtr, value);
    } 
    get {
      int ret = bwapiclientPINVOKE.BWAPIC_UnitCommand_unitIndex_get(swigCPtr);
      return ret;
    } 
  }

  public int targetIndex {
    set {
      bwapiclientPINVOKE.BWAPIC_UnitCommand_targetIndex_set(swigCPtr, value);
    } 
    get {
      int ret = bwapiclientPINVOKE.BWAPIC_UnitCommand_targetIndex_get(swigCPtr);
      return ret;
    } 
  }

  public int x {
    set {
      bwapiclientPINVOKE.BWAPIC_UnitCommand_x_set(swigCPtr, value);
    } 
    get {
      int ret = bwapiclientPINVOKE.BWAPIC_UnitCommand_x_get(swigCPtr);
      return ret;
    } 
  }

  public int y {
    set {
      bwapiclientPINVOKE.BWAPIC_UnitCommand_y_set(swigCPtr, value);
    } 
    get {
      int ret = bwapiclientPINVOKE.BWAPIC_UnitCommand_y_get(swigCPtr);
      return ret;
    } 
  }

  public int extra {
    set {
      bwapiclientPINVOKE.BWAPIC_UnitCommand_extra_set(swigCPtr, value);
    } 
    get {
      int ret = bwapiclientPINVOKE.BWAPIC_UnitCommand_extra_get(swigCPtr);
      return ret;
    } 
  }

  public BWAPIC_UnitCommand() : this(bwapiclientPINVOKE.new_BWAPIC_UnitCommand(), true) {
  }

}

}
