//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace SWIG.BWAPIC {
 
	// defaults
	using System; 
	using System.Runtime.InteropServices; 
	// BWAPI
	using BWAPI;

public partial class Command : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Command(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Command obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Command() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          bwapiclientPINVOKE.delete_Command(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  
public override int GetHashCode()
{
   return this.swigCPtr.Handle.GetHashCode();
}

public override bool Equals(object obj)
{
    bool equal = false;
    if (obj is Command)
      equal = (((Command)obj).swigCPtr.Handle == this.swigCPtr.Handle);
    return equal;
}
  
public bool Equals(Command obj) 
{
    if (obj == null) return false;
    return (obj.swigCPtr.Handle == this.swigCPtr.Handle);
}

public static bool operator ==(Command obj1, Command obj2)
{
    if (object.ReferenceEquals(obj1, obj2)) return true;
    if (object.ReferenceEquals(obj1, null)) return false;
    if (object.ReferenceEquals(obj2, null)) return false;
   
    return obj1.Equals(obj2);
}

public static bool operator !=(Command obj1, Command obj2)
{
    if (object.ReferenceEquals(obj1, obj2)) return false;
    if (object.ReferenceEquals(obj1, null)) return true;
    if (object.ReferenceEquals(obj2, null)) return true;

    return !obj1.Equals(obj2);
}




  public Command() : this(bwapiclientPINVOKE.new_Command__SWIG_0(), true) {
  }

  public Command(CommandType_Enum _commandType, int _value1, int _value2) : this(bwapiclientPINVOKE.new_Command__SWIG_1((int)_commandType, _value1, _value2), true) {
  }

  public Command(CommandType_Enum _commandType, int _value1) : this(bwapiclientPINVOKE.new_Command__SWIG_2((int)_commandType, _value1), true) {
  }

  public Command(CommandType_Enum _commandType) : this(bwapiclientPINVOKE.new_Command__SWIG_3((int)_commandType), true) {
  }

  public CommandType_Enum type {
    set {
      bwapiclientPINVOKE.Command_type_set(swigCPtr, (int)value);
    } 
    get {
      CommandType_Enum ret = (CommandType_Enum)bwapiclientPINVOKE.Command_type_get(swigCPtr);
      return ret;
    } 
  }

  public int value1 {
    set {
      bwapiclientPINVOKE.Command_value1_set(swigCPtr, value);
    } 
    get {
      int ret = bwapiclientPINVOKE.Command_value1_get(swigCPtr);
      return ret;
    } 
  }

  public int value2 {
    set {
      bwapiclientPINVOKE.Command_value2_set(swigCPtr, value);
    } 
    get {
      int ret = bwapiclientPINVOKE.Command_value2_get(swigCPtr);
      return ret;
    } 
  }

}

}
