//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace SWIG.BWAPIC {
 
	// defaults
	using System; 
	using System.Runtime.InteropServices; 
	// BWAPI
	using BWAPI;

public partial class UnitImpl : Unit {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal UnitImpl(global::System.IntPtr cPtr, bool cMemoryOwn) : base(bwapiclientPINVOKE.UnitImpl_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(UnitImpl obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~UnitImpl() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          bwapiclientPINVOKE.delete_UnitImpl(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  
public override int GetHashCode()
{
   return this.swigCPtr.Handle.GetHashCode();
}

public override bool Equals(object obj)
{
    bool equal = false;
    if (obj is UnitImpl)
      equal = (((UnitImpl)obj).swigCPtr.Handle == this.swigCPtr.Handle);
    return equal;
}
  
public bool Equals(UnitImpl obj) 
{
    if (obj == null) return false;
    return (obj.swigCPtr.Handle == this.swigCPtr.Handle);
}

public static bool operator ==(UnitImpl obj1, UnitImpl obj2)
{
    if (object.ReferenceEquals(obj1, obj2)) return true;
    if (object.ReferenceEquals(obj1, null)) return false;
    if (object.ReferenceEquals(obj2, null)) return false;
   
    return obj1.Equals(obj2);
}

public static bool operator !=(UnitImpl obj1, UnitImpl obj2)
{
    if (object.ReferenceEquals(obj1, obj2)) return false;
    if (object.ReferenceEquals(obj1, null)) return true;
    if (object.ReferenceEquals(obj2, null)) return true;

    return !obj1.Equals(obj2);
}




  public UnitData self {
    set {
      bwapiclientPINVOKE.UnitImpl_self_set(swigCPtr, UnitData.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = bwapiclientPINVOKE.UnitImpl_self_get(swigCPtr);
      UnitData ret = (cPtr == global::System.IntPtr.Zero) ? null : new UnitData(cPtr, false);
      return ret;
    } 
  }

  public UnitPtrSet connectedUnits {
    set {
      bwapiclientPINVOKE.UnitImpl_connectedUnits_set(swigCPtr, UnitPtrSet.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = bwapiclientPINVOKE.UnitImpl_connectedUnits_get(swigCPtr);
      UnitPtrSet ret = (cPtr == global::System.IntPtr.Zero) ? null : new UnitPtrSet(cPtr, false);
      return ret;
    } 
  }

  public UnitPtrSet loadedUnits {
    set {
      bwapiclientPINVOKE.UnitImpl_loadedUnits_set(swigCPtr, UnitPtrSet.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = bwapiclientPINVOKE.UnitImpl_loadedUnits_get(swigCPtr);
      UnitPtrSet ret = (cPtr == global::System.IntPtr.Zero) ? null : new UnitPtrSet(cPtr, false);
      return ret;
    } 
  }

  public void clear() {
    bwapiclientPINVOKE.UnitImpl_clear(swigCPtr);
  }

  public void saveInitialState() {
    bwapiclientPINVOKE.UnitImpl_saveInitialState(swigCPtr);
  }

  public UnitImpl(int id) : this(bwapiclientPINVOKE.new_UnitImpl(id), true) {
  }

  public override int getID() {
    int ret = bwapiclientPINVOKE.UnitImpl_getID(swigCPtr);
    return ret;
  }

  public override int getReplayID() {
    int ret = bwapiclientPINVOKE.UnitImpl_getReplayID(swigCPtr);
    return ret;
  }

  public override Player getPlayer() {
    global::System.IntPtr cPtr = bwapiclientPINVOKE.UnitImpl_getPlayer(swigCPtr);
    Player ret = (cPtr == global::System.IntPtr.Zero) ? null : new Player(cPtr, false);
    return ret;
  }

  public override UnitType getType() {
    UnitType ret = new UnitType(bwapiclientPINVOKE.UnitImpl_getType(swigCPtr), true);
    return ret;
  }

  public override Position getPosition() {
    Position ret = new Position(bwapiclientPINVOKE.UnitImpl_getPosition(swigCPtr), true);
    return ret;
  }

  public override TilePosition getTilePosition() {
    TilePosition ret = new TilePosition(bwapiclientPINVOKE.UnitImpl_getTilePosition(swigCPtr), true);
    return ret;
  }

  public override double getAngle() {
    double ret = bwapiclientPINVOKE.UnitImpl_getAngle(swigCPtr);
    return ret;
  }

  public override double getVelocityX() {
    double ret = bwapiclientPINVOKE.UnitImpl_getVelocityX(swigCPtr);
    return ret;
  }

  public override double getVelocityY() {
    double ret = bwapiclientPINVOKE.UnitImpl_getVelocityY(swigCPtr);
    return ret;
  }

  public override SWIGTYPE_p_BWAPI__Region getRegion() {
    global::System.IntPtr cPtr = bwapiclientPINVOKE.UnitImpl_getRegion(swigCPtr);
    SWIGTYPE_p_BWAPI__Region ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_BWAPI__Region(cPtr, false);
    return ret;
  }

  public override int getLeft() {
    int ret = bwapiclientPINVOKE.UnitImpl_getLeft(swigCPtr);
    return ret;
  }

  public override int getTop() {
    int ret = bwapiclientPINVOKE.UnitImpl_getTop(swigCPtr);
    return ret;
  }

  public override int getRight() {
    int ret = bwapiclientPINVOKE.UnitImpl_getRight(swigCPtr);
    return ret;
  }

  public override int getBottom() {
    int ret = bwapiclientPINVOKE.UnitImpl_getBottom(swigCPtr);
    return ret;
  }

  public override int getHitPoints() {
    int ret = bwapiclientPINVOKE.UnitImpl_getHitPoints(swigCPtr);
    return ret;
  }

  public override int getShields() {
    int ret = bwapiclientPINVOKE.UnitImpl_getShields(swigCPtr);
    return ret;
  }

  public override int getEnergy() {
    int ret = bwapiclientPINVOKE.UnitImpl_getEnergy(swigCPtr);
    return ret;
  }

  public override int getResources() {
    int ret = bwapiclientPINVOKE.UnitImpl_getResources(swigCPtr);
    return ret;
  }

  public override int getResourceGroup() {
    int ret = bwapiclientPINVOKE.UnitImpl_getResourceGroup(swigCPtr);
    return ret;
  }

  public override int getDistance(Unit target) {
    int ret = bwapiclientPINVOKE.UnitImpl_getDistance__SWIG_0(swigCPtr, Unit.getCPtr(target));
    return ret;
  }

  public override int getDistance(Position target) {
    int ret = bwapiclientPINVOKE.UnitImpl_getDistance__SWIG_1(swigCPtr, Position.getCPtr(target));
    if (bwapiclientPINVOKE.SWIGPendingException.Pending) throw bwapiclientPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override bool hasPath(Unit target) {
    bool ret = bwapiclientPINVOKE.UnitImpl_hasPath__SWIG_0(swigCPtr, Unit.getCPtr(target));
    return ret;
  }

  public override bool hasPath(Position target) {
    bool ret = bwapiclientPINVOKE.UnitImpl_hasPath__SWIG_1(swigCPtr, Position.getCPtr(target));
    if (bwapiclientPINVOKE.SWIGPendingException.Pending) throw bwapiclientPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override int getLastCommandFrame() {
    int ret = bwapiclientPINVOKE.UnitImpl_getLastCommandFrame(swigCPtr);
    return ret;
  }

  public override UnitCommand getLastCommand() {
    UnitCommand ret = new UnitCommand(bwapiclientPINVOKE.UnitImpl_getLastCommand(swigCPtr), true);
    return ret;
  }

  public override Player getLastAttackingPlayer() {
    global::System.IntPtr cPtr = bwapiclientPINVOKE.UnitImpl_getLastAttackingPlayer(swigCPtr);
    Player ret = (cPtr == global::System.IntPtr.Zero) ? null : new Player(cPtr, false);
    return ret;
  }

  public override int getUpgradeLevel(UpgradeType upgrade) {
    int ret = bwapiclientPINVOKE.UnitImpl_getUpgradeLevel(swigCPtr, UpgradeType.getCPtr(upgrade));
    if (bwapiclientPINVOKE.SWIGPendingException.Pending) throw bwapiclientPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override UnitType getInitialType() {
    UnitType ret = new UnitType(bwapiclientPINVOKE.UnitImpl_getInitialType(swigCPtr), true);
    return ret;
  }

  public override Position getInitialPosition() {
    Position ret = new Position(bwapiclientPINVOKE.UnitImpl_getInitialPosition(swigCPtr), true);
    return ret;
  }

  public override TilePosition getInitialTilePosition() {
    TilePosition ret = new TilePosition(bwapiclientPINVOKE.UnitImpl_getInitialTilePosition(swigCPtr), true);
    return ret;
  }

  public override int getInitialHitPoints() {
    int ret = bwapiclientPINVOKE.UnitImpl_getInitialHitPoints(swigCPtr);
    return ret;
  }

  public override int getInitialResources() {
    int ret = bwapiclientPINVOKE.UnitImpl_getInitialResources(swigCPtr);
    return ret;
  }

  public override int getKillCount() {
    int ret = bwapiclientPINVOKE.UnitImpl_getKillCount(swigCPtr);
    return ret;
  }

  public override int getAcidSporeCount() {
    int ret = bwapiclientPINVOKE.UnitImpl_getAcidSporeCount(swigCPtr);
    return ret;
  }

  public override int getInterceptorCount() {
    int ret = bwapiclientPINVOKE.UnitImpl_getInterceptorCount(swigCPtr);
    return ret;
  }

  public override int getScarabCount() {
    int ret = bwapiclientPINVOKE.UnitImpl_getScarabCount(swigCPtr);
    return ret;
  }

  public override int getSpiderMineCount() {
    int ret = bwapiclientPINVOKE.UnitImpl_getSpiderMineCount(swigCPtr);
    return ret;
  }

  public override int getGroundWeaponCooldown() {
    int ret = bwapiclientPINVOKE.UnitImpl_getGroundWeaponCooldown(swigCPtr);
    return ret;
  }

  public override int getAirWeaponCooldown() {
    int ret = bwapiclientPINVOKE.UnitImpl_getAirWeaponCooldown(swigCPtr);
    return ret;
  }

  public override int getSpellCooldown() {
    int ret = bwapiclientPINVOKE.UnitImpl_getSpellCooldown(swigCPtr);
    return ret;
  }

  public override int getDefenseMatrixPoints() {
    int ret = bwapiclientPINVOKE.UnitImpl_getDefenseMatrixPoints(swigCPtr);
    return ret;
  }

  public override int getDefenseMatrixTimer() {
    int ret = bwapiclientPINVOKE.UnitImpl_getDefenseMatrixTimer(swigCPtr);
    return ret;
  }

  public override int getEnsnareTimer() {
    int ret = bwapiclientPINVOKE.UnitImpl_getEnsnareTimer(swigCPtr);
    return ret;
  }

  public override int getIrradiateTimer() {
    int ret = bwapiclientPINVOKE.UnitImpl_getIrradiateTimer(swigCPtr);
    return ret;
  }

  public override int getLockdownTimer() {
    int ret = bwapiclientPINVOKE.UnitImpl_getLockdownTimer(swigCPtr);
    return ret;
  }

  public override int getMaelstromTimer() {
    int ret = bwapiclientPINVOKE.UnitImpl_getMaelstromTimer(swigCPtr);
    return ret;
  }

  public override int getOrderTimer() {
    int ret = bwapiclientPINVOKE.UnitImpl_getOrderTimer(swigCPtr);
    return ret;
  }

  public override int getPlagueTimer() {
    int ret = bwapiclientPINVOKE.UnitImpl_getPlagueTimer(swigCPtr);
    return ret;
  }

  public override int getRemoveTimer() {
    int ret = bwapiclientPINVOKE.UnitImpl_getRemoveTimer(swigCPtr);
    return ret;
  }

  public override int getStasisTimer() {
    int ret = bwapiclientPINVOKE.UnitImpl_getStasisTimer(swigCPtr);
    return ret;
  }

  public override int getStimTimer() {
    int ret = bwapiclientPINVOKE.UnitImpl_getStimTimer(swigCPtr);
    return ret;
  }

  public override UnitType getBuildType() {
    UnitType ret = new UnitType(bwapiclientPINVOKE.UnitImpl_getBuildType(swigCPtr), true);
    return ret;
  }

  public override UnitTypeList getTrainingQueue() {
    UnitTypeList ret = new UnitTypeList(bwapiclientPINVOKE.UnitImpl_getTrainingQueue(swigCPtr), true);
    return ret;
  }

  public override TechType getTech() {
    TechType ret = new TechType(bwapiclientPINVOKE.UnitImpl_getTech(swigCPtr), true);
    return ret;
  }

  public override UpgradeType getUpgrade() {
    UpgradeType ret = new UpgradeType(bwapiclientPINVOKE.UnitImpl_getUpgrade(swigCPtr), true);
    return ret;
  }

  public override int getRemainingBuildTime() {
    int ret = bwapiclientPINVOKE.UnitImpl_getRemainingBuildTime(swigCPtr);
    return ret;
  }

  public override int getRemainingTrainTime() {
    int ret = bwapiclientPINVOKE.UnitImpl_getRemainingTrainTime(swigCPtr);
    return ret;
  }

  public override int getRemainingResearchTime() {
    int ret = bwapiclientPINVOKE.UnitImpl_getRemainingResearchTime(swigCPtr);
    return ret;
  }

  public override int getRemainingUpgradeTime() {
    int ret = bwapiclientPINVOKE.UnitImpl_getRemainingUpgradeTime(swigCPtr);
    return ret;
  }

  public override Unit getBuildUnit() {
    global::System.IntPtr cPtr = bwapiclientPINVOKE.UnitImpl_getBuildUnit(swigCPtr);
    Unit ret = (cPtr == global::System.IntPtr.Zero) ? null : new Unit(cPtr, false);
    return ret;
  }

  public override Unit getTarget() {
    global::System.IntPtr cPtr = bwapiclientPINVOKE.UnitImpl_getTarget(swigCPtr);
    Unit ret = (cPtr == global::System.IntPtr.Zero) ? null : new Unit(cPtr, false);
    return ret;
  }

  public override Position getTargetPosition() {
    Position ret = new Position(bwapiclientPINVOKE.UnitImpl_getTargetPosition(swigCPtr), true);
    return ret;
  }

  public override Order getOrder() {
    Order ret = new Order(bwapiclientPINVOKE.UnitImpl_getOrder(swigCPtr), true);
    return ret;
  }

  public override Unit getOrderTarget() {
    global::System.IntPtr cPtr = bwapiclientPINVOKE.UnitImpl_getOrderTarget(swigCPtr);
    Unit ret = (cPtr == global::System.IntPtr.Zero) ? null : new Unit(cPtr, false);
    return ret;
  }

  public override Position getOrderTargetPosition() {
    Position ret = new Position(bwapiclientPINVOKE.UnitImpl_getOrderTargetPosition(swigCPtr), true);
    return ret;
  }

  public override Order getSecondaryOrder() {
    Order ret = new Order(bwapiclientPINVOKE.UnitImpl_getSecondaryOrder(swigCPtr), true);
    return ret;
  }

  public override Position getRallyPosition() {
    Position ret = new Position(bwapiclientPINVOKE.UnitImpl_getRallyPosition(swigCPtr), true);
    return ret;
  }

  public override Unit getRallyUnit() {
    global::System.IntPtr cPtr = bwapiclientPINVOKE.UnitImpl_getRallyUnit(swigCPtr);
    Unit ret = (cPtr == global::System.IntPtr.Zero) ? null : new Unit(cPtr, false);
    return ret;
  }

  public override Unit getAddon() {
    global::System.IntPtr cPtr = bwapiclientPINVOKE.UnitImpl_getAddon(swigCPtr);
    Unit ret = (cPtr == global::System.IntPtr.Zero) ? null : new Unit(cPtr, false);
    return ret;
  }

  public override Unit getNydusExit() {
    global::System.IntPtr cPtr = bwapiclientPINVOKE.UnitImpl_getNydusExit(swigCPtr);
    Unit ret = (cPtr == global::System.IntPtr.Zero) ? null : new Unit(cPtr, false);
    return ret;
  }

  public override Unit getPowerUp() {
    global::System.IntPtr cPtr = bwapiclientPINVOKE.UnitImpl_getPowerUp(swigCPtr);
    Unit ret = (cPtr == global::System.IntPtr.Zero) ? null : new Unit(cPtr, false);
    return ret;
  }

  public override Unit getTransport() {
    global::System.IntPtr cPtr = bwapiclientPINVOKE.UnitImpl_getTransport(swigCPtr);
    Unit ret = (cPtr == global::System.IntPtr.Zero) ? null : new Unit(cPtr, false);
    return ret;
  }

  public override UnitPtrSet getLoadedUnits() {
    UnitPtrSet ret = new UnitPtrSet(bwapiclientPINVOKE.UnitImpl_getLoadedUnits(swigCPtr), true);
    return ret;
  }

  public override Unit getCarrier() {
    global::System.IntPtr cPtr = bwapiclientPINVOKE.UnitImpl_getCarrier(swigCPtr);
    Unit ret = (cPtr == global::System.IntPtr.Zero) ? null : new Unit(cPtr, false);
    return ret;
  }

  public override UnitPtrSet getInterceptors() {
    UnitPtrSet ret = new UnitPtrSet(bwapiclientPINVOKE.UnitImpl_getInterceptors(swigCPtr), true);
    return ret;
  }

  public override Unit getHatchery() {
    global::System.IntPtr cPtr = bwapiclientPINVOKE.UnitImpl_getHatchery(swigCPtr);
    Unit ret = (cPtr == global::System.IntPtr.Zero) ? null : new Unit(cPtr, false);
    return ret;
  }

  public override UnitPtrSet getLarva() {
    UnitPtrSet ret = new UnitPtrSet(bwapiclientPINVOKE.UnitImpl_getLarva(swigCPtr), true);
    return ret;
  }

  public override UnitPtrSet getUnitsInRadius(int radius) {
    UnitPtrSet ret = new UnitPtrSet(bwapiclientPINVOKE.UnitImpl_getUnitsInRadius(swigCPtr, radius), false);
    return ret;
  }

  public override UnitPtrSet getUnitsInWeaponRange(WeaponType weapon) {
    UnitPtrSet ret = new UnitPtrSet(bwapiclientPINVOKE.UnitImpl_getUnitsInWeaponRange(swigCPtr, WeaponType.getCPtr(weapon)), false);
    if (bwapiclientPINVOKE.SWIGPendingException.Pending) throw bwapiclientPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override SWIGTYPE_p_void getClientInfo() {
    global::System.IntPtr cPtr = bwapiclientPINVOKE.UnitImpl_getClientInfo(swigCPtr);
    SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
    return ret;
  }

  public override void setClientInfo(SWIGTYPE_p_void clientinfo) {
    bwapiclientPINVOKE.UnitImpl_setClientInfo(swigCPtr, SWIGTYPE_p_void.getCPtr(clientinfo));
  }

  public override bool exists() {
    bool ret = bwapiclientPINVOKE.UnitImpl_exists(swigCPtr);
    return ret;
  }

  public override bool hasNuke() {
    bool ret = bwapiclientPINVOKE.UnitImpl_hasNuke(swigCPtr);
    return ret;
  }

  public override bool isAccelerating() {
    bool ret = bwapiclientPINVOKE.UnitImpl_isAccelerating(swigCPtr);
    return ret;
  }

  public override bool isAttackFrame() {
    bool ret = bwapiclientPINVOKE.UnitImpl_isAttackFrame(swigCPtr);
    return ret;
  }

  public override bool isAttacking() {
    bool ret = bwapiclientPINVOKE.UnitImpl_isAttacking(swigCPtr);
    return ret;
  }

  public override bool isBeingConstructed() {
    bool ret = bwapiclientPINVOKE.UnitImpl_isBeingConstructed(swigCPtr);
    return ret;
  }

  public override bool isBeingGathered() {
    bool ret = bwapiclientPINVOKE.UnitImpl_isBeingGathered(swigCPtr);
    return ret;
  }

  public override bool isBeingHealed() {
    bool ret = bwapiclientPINVOKE.UnitImpl_isBeingHealed(swigCPtr);
    return ret;
  }

  public override bool isBlind() {
    bool ret = bwapiclientPINVOKE.UnitImpl_isBlind(swigCPtr);
    return ret;
  }

  public override bool isBraking() {
    bool ret = bwapiclientPINVOKE.UnitImpl_isBraking(swigCPtr);
    return ret;
  }

  public override bool isBurrowed() {
    bool ret = bwapiclientPINVOKE.UnitImpl_isBurrowed(swigCPtr);
    return ret;
  }

  public override bool isCarryingGas() {
    bool ret = bwapiclientPINVOKE.UnitImpl_isCarryingGas(swigCPtr);
    return ret;
  }

  public override bool isCarryingMinerals() {
    bool ret = bwapiclientPINVOKE.UnitImpl_isCarryingMinerals(swigCPtr);
    return ret;
  }

  public override bool isCloaked() {
    bool ret = bwapiclientPINVOKE.UnitImpl_isCloaked(swigCPtr);
    return ret;
  }

  public override bool isCompleted() {
    bool ret = bwapiclientPINVOKE.UnitImpl_isCompleted(swigCPtr);
    return ret;
  }

  public override bool isConstructing() {
    bool ret = bwapiclientPINVOKE.UnitImpl_isConstructing(swigCPtr);
    return ret;
  }

  public override bool isDefenseMatrixed() {
    bool ret = bwapiclientPINVOKE.UnitImpl_isDefenseMatrixed(swigCPtr);
    return ret;
  }

  public override bool isDetected() {
    bool ret = bwapiclientPINVOKE.UnitImpl_isDetected(swigCPtr);
    return ret;
  }

  public override bool isEnsnared() {
    bool ret = bwapiclientPINVOKE.UnitImpl_isEnsnared(swigCPtr);
    return ret;
  }

  public override bool isFollowing() {
    bool ret = bwapiclientPINVOKE.UnitImpl_isFollowing(swigCPtr);
    return ret;
  }

  public override bool isGatheringGas() {
    bool ret = bwapiclientPINVOKE.UnitImpl_isGatheringGas(swigCPtr);
    return ret;
  }

  public override bool isGatheringMinerals() {
    bool ret = bwapiclientPINVOKE.UnitImpl_isGatheringMinerals(swigCPtr);
    return ret;
  }

  public override bool isHallucination() {
    bool ret = bwapiclientPINVOKE.UnitImpl_isHallucination(swigCPtr);
    return ret;
  }

  public override bool isHoldingPosition() {
    bool ret = bwapiclientPINVOKE.UnitImpl_isHoldingPosition(swigCPtr);
    return ret;
  }

  public override bool isIdle() {
    bool ret = bwapiclientPINVOKE.UnitImpl_isIdle(swigCPtr);
    return ret;
  }

  public override bool isInWeaponRange(Unit target) {
    bool ret = bwapiclientPINVOKE.UnitImpl_isInWeaponRange(swigCPtr, Unit.getCPtr(target));
    return ret;
  }

  public override bool isInterruptible() {
    bool ret = bwapiclientPINVOKE.UnitImpl_isInterruptible(swigCPtr);
    return ret;
  }

  public override bool isInvincible() {
    bool ret = bwapiclientPINVOKE.UnitImpl_isInvincible(swigCPtr);
    return ret;
  }

  public override bool isIrradiated() {
    bool ret = bwapiclientPINVOKE.UnitImpl_isIrradiated(swigCPtr);
    return ret;
  }

  public override bool isLifted() {
    bool ret = bwapiclientPINVOKE.UnitImpl_isLifted(swigCPtr);
    return ret;
  }

  public override bool isLoaded() {
    bool ret = bwapiclientPINVOKE.UnitImpl_isLoaded(swigCPtr);
    return ret;
  }

  public override bool isLockedDown() {
    bool ret = bwapiclientPINVOKE.UnitImpl_isLockedDown(swigCPtr);
    return ret;
  }

  public override bool isMaelstrommed() {
    bool ret = bwapiclientPINVOKE.UnitImpl_isMaelstrommed(swigCPtr);
    return ret;
  }

  public override bool isMorphing() {
    bool ret = bwapiclientPINVOKE.UnitImpl_isMorphing(swigCPtr);
    return ret;
  }

  public override bool isMoving() {
    bool ret = bwapiclientPINVOKE.UnitImpl_isMoving(swigCPtr);
    return ret;
  }

  public override bool isParasited() {
    bool ret = bwapiclientPINVOKE.UnitImpl_isParasited(swigCPtr);
    return ret;
  }

  public override bool isPatrolling() {
    bool ret = bwapiclientPINVOKE.UnitImpl_isPatrolling(swigCPtr);
    return ret;
  }

  public override bool isPlagued() {
    bool ret = bwapiclientPINVOKE.UnitImpl_isPlagued(swigCPtr);
    return ret;
  }

  public override bool isRepairing() {
    bool ret = bwapiclientPINVOKE.UnitImpl_isRepairing(swigCPtr);
    return ret;
  }

  public override bool isResearching() {
    bool ret = bwapiclientPINVOKE.UnitImpl_isResearching(swigCPtr);
    return ret;
  }

  public override bool isSelected() {
    bool ret = bwapiclientPINVOKE.UnitImpl_isSelected(swigCPtr);
    return ret;
  }

  public override bool isSieged() {
    bool ret = bwapiclientPINVOKE.UnitImpl_isSieged(swigCPtr);
    return ret;
  }

  public override bool isStartingAttack() {
    bool ret = bwapiclientPINVOKE.UnitImpl_isStartingAttack(swigCPtr);
    return ret;
  }

  public override bool isStasised() {
    bool ret = bwapiclientPINVOKE.UnitImpl_isStasised(swigCPtr);
    return ret;
  }

  public override bool isStimmed() {
    bool ret = bwapiclientPINVOKE.UnitImpl_isStimmed(swigCPtr);
    return ret;
  }

  public override bool isStuck() {
    bool ret = bwapiclientPINVOKE.UnitImpl_isStuck(swigCPtr);
    return ret;
  }

  public override bool isTraining() {
    bool ret = bwapiclientPINVOKE.UnitImpl_isTraining(swigCPtr);
    return ret;
  }

  public override bool isUnderAttack() {
    bool ret = bwapiclientPINVOKE.UnitImpl_isUnderAttack(swigCPtr);
    return ret;
  }

  public override bool isUnderDarkSwarm() {
    bool ret = bwapiclientPINVOKE.UnitImpl_isUnderDarkSwarm(swigCPtr);
    return ret;
  }

  public override bool isUnderDisruptionWeb() {
    bool ret = bwapiclientPINVOKE.UnitImpl_isUnderDisruptionWeb(swigCPtr);
    return ret;
  }

  public override bool isUnderStorm() {
    bool ret = bwapiclientPINVOKE.UnitImpl_isUnderStorm(swigCPtr);
    return ret;
  }

  public override bool isUnpowered() {
    bool ret = bwapiclientPINVOKE.UnitImpl_isUnpowered(swigCPtr);
    return ret;
  }

  public override bool isUpgrading() {
    bool ret = bwapiclientPINVOKE.UnitImpl_isUpgrading(swigCPtr);
    return ret;
  }

  public override bool isVisible() {
    bool ret = bwapiclientPINVOKE.UnitImpl_isVisible__SWIG_0(swigCPtr);
    return ret;
  }

  public override bool isVisible(Player player) {
    bool ret = bwapiclientPINVOKE.UnitImpl_isVisible__SWIG_1(swigCPtr, Player.getCPtr(player));
    return ret;
  }

  public override bool canIssueCommand(UnitCommand command) {
    bool ret = bwapiclientPINVOKE.UnitImpl_canIssueCommand(swigCPtr, UnitCommand.getCPtr(command));
    if (bwapiclientPINVOKE.SWIGPendingException.Pending) throw bwapiclientPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override bool issueCommand(UnitCommand command) {
    bool ret = bwapiclientPINVOKE.UnitImpl_issueCommand(swigCPtr, UnitCommand.getCPtr(command));
    if (bwapiclientPINVOKE.SWIGPendingException.Pending) throw bwapiclientPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override bool attack(Position target, bool shiftQueueCommand) {
    bool ret = bwapiclientPINVOKE.UnitImpl_attack__SWIG_0(swigCPtr, Position.getCPtr(target), shiftQueueCommand);
    if (bwapiclientPINVOKE.SWIGPendingException.Pending) throw bwapiclientPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override bool attack(Position target) {
    bool ret = bwapiclientPINVOKE.UnitImpl_attack__SWIG_1(swigCPtr, Position.getCPtr(target));
    if (bwapiclientPINVOKE.SWIGPendingException.Pending) throw bwapiclientPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override bool attack(Unit target, bool shiftQueueCommand) {
    bool ret = bwapiclientPINVOKE.UnitImpl_attack__SWIG_2(swigCPtr, Unit.getCPtr(target), shiftQueueCommand);
    return ret;
  }

  public override bool attack(Unit target) {
    bool ret = bwapiclientPINVOKE.UnitImpl_attack__SWIG_3(swigCPtr, Unit.getCPtr(target));
    return ret;
  }

  public override bool build(TilePosition target, UnitType type) {
    bool ret = bwapiclientPINVOKE.UnitImpl_build(swigCPtr, TilePosition.getCPtr(target), UnitType.getCPtr(type));
    if (bwapiclientPINVOKE.SWIGPendingException.Pending) throw bwapiclientPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override bool buildAddon(UnitType type) {
    bool ret = bwapiclientPINVOKE.UnitImpl_buildAddon(swigCPtr, UnitType.getCPtr(type));
    if (bwapiclientPINVOKE.SWIGPendingException.Pending) throw bwapiclientPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override bool train(UnitType type) {
    bool ret = bwapiclientPINVOKE.UnitImpl_train(swigCPtr, UnitType.getCPtr(type));
    if (bwapiclientPINVOKE.SWIGPendingException.Pending) throw bwapiclientPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override bool morph(UnitType type) {
    bool ret = bwapiclientPINVOKE.UnitImpl_morph(swigCPtr, UnitType.getCPtr(type));
    if (bwapiclientPINVOKE.SWIGPendingException.Pending) throw bwapiclientPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override bool research(TechType tech) {
    bool ret = bwapiclientPINVOKE.UnitImpl_research(swigCPtr, TechType.getCPtr(tech));
    if (bwapiclientPINVOKE.SWIGPendingException.Pending) throw bwapiclientPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override bool upgrade(UpgradeType upgrade) {
    bool ret = bwapiclientPINVOKE.UnitImpl_upgrade(swigCPtr, UpgradeType.getCPtr(upgrade));
    if (bwapiclientPINVOKE.SWIGPendingException.Pending) throw bwapiclientPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override bool setRallyPoint(Position target) {
    bool ret = bwapiclientPINVOKE.UnitImpl_setRallyPoint__SWIG_0(swigCPtr, Position.getCPtr(target));
    if (bwapiclientPINVOKE.SWIGPendingException.Pending) throw bwapiclientPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override bool setRallyPoint(Unit target) {
    bool ret = bwapiclientPINVOKE.UnitImpl_setRallyPoint__SWIG_1(swigCPtr, Unit.getCPtr(target));
    return ret;
  }

  public override bool move(Position target, bool shiftQueueCommand) {
    bool ret = bwapiclientPINVOKE.UnitImpl_move__SWIG_0(swigCPtr, Position.getCPtr(target), shiftQueueCommand);
    if (bwapiclientPINVOKE.SWIGPendingException.Pending) throw bwapiclientPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override bool move(Position target) {
    bool ret = bwapiclientPINVOKE.UnitImpl_move__SWIG_1(swigCPtr, Position.getCPtr(target));
    if (bwapiclientPINVOKE.SWIGPendingException.Pending) throw bwapiclientPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override bool patrol(Position target, bool shiftQueueCommand) {
    bool ret = bwapiclientPINVOKE.UnitImpl_patrol__SWIG_0(swigCPtr, Position.getCPtr(target), shiftQueueCommand);
    if (bwapiclientPINVOKE.SWIGPendingException.Pending) throw bwapiclientPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override bool patrol(Position target) {
    bool ret = bwapiclientPINVOKE.UnitImpl_patrol__SWIG_1(swigCPtr, Position.getCPtr(target));
    if (bwapiclientPINVOKE.SWIGPendingException.Pending) throw bwapiclientPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override bool holdPosition(bool shiftQueueCommand) {
    bool ret = bwapiclientPINVOKE.UnitImpl_holdPosition__SWIG_0(swigCPtr, shiftQueueCommand);
    return ret;
  }

  public override bool holdPosition() {
    bool ret = bwapiclientPINVOKE.UnitImpl_holdPosition__SWIG_1(swigCPtr);
    return ret;
  }

  public override bool stop(bool shiftQueueCommand) {
    bool ret = bwapiclientPINVOKE.UnitImpl_stop__SWIG_0(swigCPtr, shiftQueueCommand);
    return ret;
  }

  public override bool stop() {
    bool ret = bwapiclientPINVOKE.UnitImpl_stop__SWIG_1(swigCPtr);
    return ret;
  }

  public override bool follow(Unit target, bool shiftQueueCommand) {
    bool ret = bwapiclientPINVOKE.UnitImpl_follow__SWIG_0(swigCPtr, Unit.getCPtr(target), shiftQueueCommand);
    return ret;
  }

  public override bool follow(Unit target) {
    bool ret = bwapiclientPINVOKE.UnitImpl_follow__SWIG_1(swigCPtr, Unit.getCPtr(target));
    return ret;
  }

  public override bool gather(Unit target, bool shiftQueueCommand) {
    bool ret = bwapiclientPINVOKE.UnitImpl_gather__SWIG_0(swigCPtr, Unit.getCPtr(target), shiftQueueCommand);
    return ret;
  }

  public override bool gather(Unit target) {
    bool ret = bwapiclientPINVOKE.UnitImpl_gather__SWIG_1(swigCPtr, Unit.getCPtr(target));
    return ret;
  }

  public override bool returnCargo(bool shiftQueueCommand) {
    bool ret = bwapiclientPINVOKE.UnitImpl_returnCargo__SWIG_0(swigCPtr, shiftQueueCommand);
    return ret;
  }

  public override bool returnCargo() {
    bool ret = bwapiclientPINVOKE.UnitImpl_returnCargo__SWIG_1(swigCPtr);
    return ret;
  }

  public override bool repair(Unit target, bool shiftQueueCommand) {
    bool ret = bwapiclientPINVOKE.UnitImpl_repair__SWIG_0(swigCPtr, Unit.getCPtr(target), shiftQueueCommand);
    return ret;
  }

  public override bool repair(Unit target) {
    bool ret = bwapiclientPINVOKE.UnitImpl_repair__SWIG_1(swigCPtr, Unit.getCPtr(target));
    return ret;
  }

  public override bool burrow() {
    bool ret = bwapiclientPINVOKE.UnitImpl_burrow(swigCPtr);
    return ret;
  }

  public override bool unburrow() {
    bool ret = bwapiclientPINVOKE.UnitImpl_unburrow(swigCPtr);
    return ret;
  }

  public override bool cloak() {
    bool ret = bwapiclientPINVOKE.UnitImpl_cloak(swigCPtr);
    return ret;
  }

  public override bool decloak() {
    bool ret = bwapiclientPINVOKE.UnitImpl_decloak(swigCPtr);
    return ret;
  }

  public override bool siege() {
    bool ret = bwapiclientPINVOKE.UnitImpl_siege(swigCPtr);
    return ret;
  }

  public override bool unsiege() {
    bool ret = bwapiclientPINVOKE.UnitImpl_unsiege(swigCPtr);
    return ret;
  }

  public override bool lift() {
    bool ret = bwapiclientPINVOKE.UnitImpl_lift(swigCPtr);
    return ret;
  }

  public override bool land(TilePosition target) {
    bool ret = bwapiclientPINVOKE.UnitImpl_land(swigCPtr, TilePosition.getCPtr(target));
    if (bwapiclientPINVOKE.SWIGPendingException.Pending) throw bwapiclientPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override bool load(Unit target, bool shiftQueueCommand) {
    bool ret = bwapiclientPINVOKE.UnitImpl_load__SWIG_0(swigCPtr, Unit.getCPtr(target), shiftQueueCommand);
    return ret;
  }

  public override bool load(Unit target) {
    bool ret = bwapiclientPINVOKE.UnitImpl_load__SWIG_1(swigCPtr, Unit.getCPtr(target));
    return ret;
  }

  public override bool unload(Unit target) {
    bool ret = bwapiclientPINVOKE.UnitImpl_unload(swigCPtr, Unit.getCPtr(target));
    return ret;
  }

  public override bool unloadAll(bool shiftQueueCommand) {
    bool ret = bwapiclientPINVOKE.UnitImpl_unloadAll__SWIG_0(swigCPtr, shiftQueueCommand);
    return ret;
  }

  public override bool unloadAll() {
    bool ret = bwapiclientPINVOKE.UnitImpl_unloadAll__SWIG_1(swigCPtr);
    return ret;
  }

  public override bool unloadAll(Position target, bool shiftQueueCommand) {
    bool ret = bwapiclientPINVOKE.UnitImpl_unloadAll__SWIG_2(swigCPtr, Position.getCPtr(target), shiftQueueCommand);
    if (bwapiclientPINVOKE.SWIGPendingException.Pending) throw bwapiclientPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override bool unloadAll(Position target) {
    bool ret = bwapiclientPINVOKE.UnitImpl_unloadAll__SWIG_3(swigCPtr, Position.getCPtr(target));
    if (bwapiclientPINVOKE.SWIGPendingException.Pending) throw bwapiclientPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override bool rightClick(Position target, bool shiftQueueCommand) {
    bool ret = bwapiclientPINVOKE.UnitImpl_rightClick__SWIG_0(swigCPtr, Position.getCPtr(target), shiftQueueCommand);
    if (bwapiclientPINVOKE.SWIGPendingException.Pending) throw bwapiclientPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override bool rightClick(Position target) {
    bool ret = bwapiclientPINVOKE.UnitImpl_rightClick__SWIG_1(swigCPtr, Position.getCPtr(target));
    if (bwapiclientPINVOKE.SWIGPendingException.Pending) throw bwapiclientPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override bool rightClick(Unit target, bool shiftQueueCommand) {
    bool ret = bwapiclientPINVOKE.UnitImpl_rightClick__SWIG_2(swigCPtr, Unit.getCPtr(target), shiftQueueCommand);
    return ret;
  }

  public override bool rightClick(Unit target) {
    bool ret = bwapiclientPINVOKE.UnitImpl_rightClick__SWIG_3(swigCPtr, Unit.getCPtr(target));
    return ret;
  }

  public override bool haltConstruction() {
    bool ret = bwapiclientPINVOKE.UnitImpl_haltConstruction(swigCPtr);
    return ret;
  }

  public override bool cancelConstruction() {
    bool ret = bwapiclientPINVOKE.UnitImpl_cancelConstruction(swigCPtr);
    return ret;
  }

  public override bool cancelAddon() {
    bool ret = bwapiclientPINVOKE.UnitImpl_cancelAddon(swigCPtr);
    return ret;
  }

  public override bool cancelTrain(int slot) {
    bool ret = bwapiclientPINVOKE.UnitImpl_cancelTrain__SWIG_0(swigCPtr, slot);
    return ret;
  }

  public override bool cancelTrain() {
    bool ret = bwapiclientPINVOKE.UnitImpl_cancelTrain__SWIG_1(swigCPtr);
    return ret;
  }

  public override bool cancelMorph() {
    bool ret = bwapiclientPINVOKE.UnitImpl_cancelMorph(swigCPtr);
    return ret;
  }

  public override bool cancelResearch() {
    bool ret = bwapiclientPINVOKE.UnitImpl_cancelResearch(swigCPtr);
    return ret;
  }

  public override bool cancelUpgrade() {
    bool ret = bwapiclientPINVOKE.UnitImpl_cancelUpgrade(swigCPtr);
    return ret;
  }

  public override bool useTech(TechType tech) {
    bool ret = bwapiclientPINVOKE.UnitImpl_useTech__SWIG_0(swigCPtr, TechType.getCPtr(tech));
    if (bwapiclientPINVOKE.SWIGPendingException.Pending) throw bwapiclientPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override bool useTech(TechType tech, Position target) {
    bool ret = bwapiclientPINVOKE.UnitImpl_useTech__SWIG_1(swigCPtr, TechType.getCPtr(tech), Position.getCPtr(target));
    if (bwapiclientPINVOKE.SWIGPendingException.Pending) throw bwapiclientPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override bool useTech(TechType tech, Unit target) {
    bool ret = bwapiclientPINVOKE.UnitImpl_useTech__SWIG_2(swigCPtr, TechType.getCPtr(tech), Unit.getCPtr(target));
    if (bwapiclientPINVOKE.SWIGPendingException.Pending) throw bwapiclientPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override bool placeCOP(TilePosition target) {
    bool ret = bwapiclientPINVOKE.UnitImpl_placeCOP(swigCPtr, TilePosition.getCPtr(target));
    if (bwapiclientPINVOKE.SWIGPendingException.Pending) throw bwapiclientPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
