//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace SWIG.BWTA {

class bwtaPINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="SWIGRegisterExceptionCallbacks_bwta")]
    public static extern void SWIGRegisterExceptionCallbacks_bwta(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_bwta")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_bwta(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_bwta(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_bwta(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(typeof(bwtaPINVOKE)) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(typeof(bwtaPINVOKE)) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="SWIGRegisterStringCallback_bwta")]
    public static extern void SWIGRegisterStringCallback_bwta(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_bwta(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static bwtaPINVOKE() {
  }


#if CLIENT
  private const string importdll = "bwapi-native.dll";
#else
  private const string importdll = "__Internal";
#endif 
  


  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_BaseLocation_getPosition")]
  public static extern global::System.IntPtr BaseLocation_getPosition(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_BaseLocation_getTilePosition")]
  public static extern global::System.IntPtr BaseLocation_getTilePosition(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_BaseLocation_getRegion")]
  public static extern global::System.IntPtr BaseLocation_getRegion(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_BaseLocation_minerals")]
  public static extern int BaseLocation_minerals(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_BaseLocation_gas")]
  public static extern int BaseLocation_gas(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_BaseLocation_getMinerals")]
  public static extern global::System.IntPtr BaseLocation_getMinerals(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_BaseLocation_getStaticMinerals")]
  public static extern global::System.IntPtr BaseLocation_getStaticMinerals(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_BaseLocation_getGeysers")]
  public static extern global::System.IntPtr BaseLocation_getGeysers(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_BaseLocation_getGroundDistance")]
  public static extern double BaseLocation_getGroundDistance(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_BaseLocation_getAirDistance")]
  public static extern double BaseLocation_getAirDistance(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_BaseLocation_isIsland")]
  public static extern bool BaseLocation_isIsland(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_BaseLocation_isMineralOnly")]
  public static extern bool BaseLocation_isMineralOnly(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_BaseLocation_isStartLocation")]
  public static extern bool BaseLocation_isStartLocation(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_delete_BaseLocation")]
  public static extern void delete_BaseLocation(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_Chokepoint_getRegions")]
  public static extern global::System.IntPtr Chokepoint_getRegions(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_Chokepoint_getSides")]
  public static extern global::System.IntPtr Chokepoint_getSides(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_Chokepoint_getCenter")]
  public static extern global::System.IntPtr Chokepoint_getCenter(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_Chokepoint_getWidth")]
  public static extern double Chokepoint_getWidth(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_delete_Chokepoint")]
  public static extern void delete_Chokepoint(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_new_Polygon__SWIG_0")]
  public static extern global::System.IntPtr new_Polygon__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_new_Polygon__SWIG_1")]
  public static extern global::System.IntPtr new_Polygon__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_Polygon_getArea")]
  public static extern double Polygon_getArea(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_Polygon_getPerimeter")]
  public static extern double Polygon_getPerimeter(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_Polygon_getCenter")]
  public static extern global::System.IntPtr Polygon_getCenter(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_Polygon_isInside")]
  public static extern bool Polygon_isInside(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_Polygon_getNearestPoint")]
  public static extern global::System.IntPtr Polygon_getNearestPoint(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_Polygon_getHoles")]
  public static extern global::System.IntPtr Polygon_getHoles(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_Polygon_holes_set")]
  public static extern void Polygon_holes_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_Polygon_holes_get")]
  public static extern global::System.IntPtr Polygon_holes_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_delete_Polygon")]
  public static extern void delete_Polygon(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_Region_getPolygon")]
  public static extern global::System.IntPtr Region_getPolygon(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_Region_getCenter")]
  public static extern global::System.IntPtr Region_getCenter(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_Region_getChokepoints")]
  public static extern global::System.IntPtr Region_getChokepoints(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_Region_getBaseLocations")]
  public static extern global::System.IntPtr Region_getBaseLocations(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_Region_isReachable")]
  public static extern bool Region_isReachable(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_Region_getReachableRegions")]
  public static extern global::System.IntPtr Region_getReachableRegions(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_delete_Region")]
  public static extern void delete_Region(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_readMap")]
  public static extern void readMap();

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_analyze")]
  public static extern void analyze();

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_getRegions")]
  public static extern global::System.IntPtr getRegions();

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_getChokepoints")]
  public static extern global::System.IntPtr getChokepoints();

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_getBaseLocations")]
  public static extern global::System.IntPtr getBaseLocations();

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_getStartLocations")]
  public static extern global::System.IntPtr getStartLocations();

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_getUnwalkablePolygons")]
  public static extern global::System.IntPtr getUnwalkablePolygons();

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_getStartLocation")]
  public static extern global::System.IntPtr getStartLocation(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_getRegion__SWIG_0")]
  public static extern global::System.IntPtr getRegion__SWIG_0(int jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_getRegion__SWIG_1")]
  public static extern global::System.IntPtr getRegion__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_getRegion__SWIG_2")]
  public static extern global::System.IntPtr getRegion__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_getNearestChokepoint__SWIG_0")]
  public static extern global::System.IntPtr getNearestChokepoint__SWIG_0(int jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_getNearestChokepoint__SWIG_1")]
  public static extern global::System.IntPtr getNearestChokepoint__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_getNearestChokepoint__SWIG_2")]
  public static extern global::System.IntPtr getNearestChokepoint__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_getNearestBaseLocation__SWIG_0")]
  public static extern global::System.IntPtr getNearestBaseLocation__SWIG_0(int jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_getNearestBaseLocation__SWIG_1")]
  public static extern global::System.IntPtr getNearestBaseLocation__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_getNearestBaseLocation__SWIG_2")]
  public static extern global::System.IntPtr getNearestBaseLocation__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_getNearestUnwalkablePolygon__SWIG_0")]
  public static extern global::System.IntPtr getNearestUnwalkablePolygon__SWIG_0(int jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_getNearestUnwalkablePolygon__SWIG_1")]
  public static extern global::System.IntPtr getNearestUnwalkablePolygon__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_getNearestUnwalkablePosition")]
  public static extern global::System.IntPtr getNearestUnwalkablePosition(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_isConnected__SWIG_0")]
  public static extern bool isConnected__SWIG_0(int jarg1, int jarg2, int jarg3, int jarg4);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_isConnected__SWIG_1")]
  public static extern bool isConnected__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_getGroundDistance")]
  public static extern double getGroundDistance(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_getNearestTilePosition")]
  public static extern global::System.IntPtr getNearestTilePosition(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_getGroundDistances")]
  public static extern global::System.IntPtr getGroundDistances(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_getGroundDistanceMap")]
  public static extern void getGroundDistanceMap(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_getGroundWalkDistanceMap")]
  public static extern void getGroundWalkDistanceMap(int jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_getShortestPath__SWIG_0")]
  public static extern global::System.IntPtr getShortestPath__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_getShortestPath__SWIG_1")]
  public static extern global::System.IntPtr getShortestPath__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_new_RectangleArrayDouble__SWIG_0")]
  public static extern global::System.IntPtr new_RectangleArrayDouble__SWIG_0(uint jarg1, uint jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_new_RectangleArrayDouble__SWIG_1")]
  public static extern global::System.IntPtr new_RectangleArrayDouble__SWIG_1(uint jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_new_RectangleArrayDouble__SWIG_2")]
  public static extern global::System.IntPtr new_RectangleArrayDouble__SWIG_2(uint jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_new_RectangleArrayDouble__SWIG_3")]
  public static extern global::System.IntPtr new_RectangleArrayDouble__SWIG_3();

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_new_RectangleArrayDouble__SWIG_4")]
  public static extern global::System.IntPtr new_RectangleArrayDouble__SWIG_4(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_delete_RectangleArrayDouble")]
  public static extern void delete_RectangleArrayDouble(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_RectangleArrayDouble_getWidth")]
  public static extern uint RectangleArrayDouble_getWidth(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_RectangleArrayDouble_getHeight")]
  public static extern uint RectangleArrayDouble_getHeight(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_RectangleArrayDouble_getItem")]
  public static extern double RectangleArrayDouble_getItem(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, uint jarg3);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_RectangleArrayDouble_getItemSafe")]
  public static extern double RectangleArrayDouble_getItemSafe(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, uint jarg3);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_RectangleArrayDouble_setItem")]
  public static extern void RectangleArrayDouble_setItem(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, uint jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_RectangleArrayDouble_resize")]
  public static extern void RectangleArrayDouble_resize(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, uint jarg3);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_RectangleArrayDouble_printToFile")]
  public static extern void RectangleArrayDouble_printToFile(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_RectangleArrayDouble_saveToFile")]
  public static extern void RectangleArrayDouble_saveToFile(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_RectangleArrayDouble_setTo")]
  public static extern void RectangleArrayDouble_setTo(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_RectangleArrayDouble_setBorderTo")]
  public static extern void RectangleArrayDouble_setBorderTo(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_new_BaseLocationPtrSet__SWIG_0")]
  public static extern global::System.IntPtr new_BaseLocationPtrSet__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_new_BaseLocationPtrSet__SWIG_1")]
  public static extern global::System.IntPtr new_BaseLocationPtrSet__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_BaseLocationPtrSet_size")]
  public static extern uint BaseLocationPtrSet_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_BaseLocationPtrSet_empty")]
  public static extern bool BaseLocationPtrSet_empty(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_BaseLocationPtrSet_Clear")]
  public static extern void BaseLocationPtrSet_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_BaseLocationPtrSet_getitem")]
  public static extern global::System.IntPtr BaseLocationPtrSet_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_BaseLocationPtrSet_ContainsKey")]
  public static extern bool BaseLocationPtrSet_ContainsKey(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_BaseLocationPtrSet_Add")]
  public static extern void BaseLocationPtrSet_Add(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_BaseLocationPtrSet_Remove")]
  public static extern bool BaseLocationPtrSet_Remove(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_BaseLocationPtrSet_create_iterator_begin")]
  public static extern global::System.IntPtr BaseLocationPtrSet_create_iterator_begin(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_BaseLocationPtrSet_get_next_key")]
  public static extern global::System.IntPtr BaseLocationPtrSet_get_next_key(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.IntPtr jarg2);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_delete_BaseLocationPtrSet")]
  public static extern void delete_BaseLocationPtrSet(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_new_RegionPtrSet__SWIG_0")]
  public static extern global::System.IntPtr new_RegionPtrSet__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_new_RegionPtrSet__SWIG_1")]
  public static extern global::System.IntPtr new_RegionPtrSet__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_RegionPtrSet_size")]
  public static extern uint RegionPtrSet_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_RegionPtrSet_empty")]
  public static extern bool RegionPtrSet_empty(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_RegionPtrSet_Clear")]
  public static extern void RegionPtrSet_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_RegionPtrSet_getitem")]
  public static extern global::System.IntPtr RegionPtrSet_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_RegionPtrSet_ContainsKey")]
  public static extern bool RegionPtrSet_ContainsKey(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_RegionPtrSet_Add")]
  public static extern void RegionPtrSet_Add(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_RegionPtrSet_Remove")]
  public static extern bool RegionPtrSet_Remove(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_RegionPtrSet_create_iterator_begin")]
  public static extern global::System.IntPtr RegionPtrSet_create_iterator_begin(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_RegionPtrSet_get_next_key")]
  public static extern global::System.IntPtr RegionPtrSet_get_next_key(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.IntPtr jarg2);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_delete_RegionPtrSet")]
  public static extern void delete_RegionPtrSet(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_new_ChokepointPtrSet__SWIG_0")]
  public static extern global::System.IntPtr new_ChokepointPtrSet__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_new_ChokepointPtrSet__SWIG_1")]
  public static extern global::System.IntPtr new_ChokepointPtrSet__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_ChokepointPtrSet_size")]
  public static extern uint ChokepointPtrSet_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_ChokepointPtrSet_empty")]
  public static extern bool ChokepointPtrSet_empty(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_ChokepointPtrSet_Clear")]
  public static extern void ChokepointPtrSet_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_ChokepointPtrSet_getitem")]
  public static extern global::System.IntPtr ChokepointPtrSet_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_ChokepointPtrSet_ContainsKey")]
  public static extern bool ChokepointPtrSet_ContainsKey(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_ChokepointPtrSet_Add")]
  public static extern void ChokepointPtrSet_Add(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_ChokepointPtrSet_Remove")]
  public static extern bool ChokepointPtrSet_Remove(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_ChokepointPtrSet_create_iterator_begin")]
  public static extern global::System.IntPtr ChokepointPtrSet_create_iterator_begin(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_ChokepointPtrSet_get_next_key")]
  public static extern global::System.IntPtr ChokepointPtrSet_get_next_key(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.IntPtr jarg2);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_delete_ChokepointPtrSet")]
  public static extern void delete_ChokepointPtrSet(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_new_PolygonPtrSet__SWIG_0")]
  public static extern global::System.IntPtr new_PolygonPtrSet__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_new_PolygonPtrSet__SWIG_1")]
  public static extern global::System.IntPtr new_PolygonPtrSet__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_PolygonPtrSet_size")]
  public static extern uint PolygonPtrSet_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_PolygonPtrSet_empty")]
  public static extern bool PolygonPtrSet_empty(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_PolygonPtrSet_Clear")]
  public static extern void PolygonPtrSet_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_PolygonPtrSet_getitem")]
  public static extern global::System.IntPtr PolygonPtrSet_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_PolygonPtrSet_ContainsKey")]
  public static extern bool PolygonPtrSet_ContainsKey(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_PolygonPtrSet_Add")]
  public static extern void PolygonPtrSet_Add(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_PolygonPtrSet_Remove")]
  public static extern bool PolygonPtrSet_Remove(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_PolygonPtrSet_create_iterator_begin")]
  public static extern global::System.IntPtr PolygonPtrSet_create_iterator_begin(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_PolygonPtrSet_get_next_key")]
  public static extern global::System.IntPtr PolygonPtrSet_get_next_key(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.IntPtr jarg2);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_delete_PolygonPtrSet")]
  public static extern void delete_PolygonPtrSet(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_PolygonVector_Clear")]
  public static extern void PolygonVector_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_PolygonVector_Add")]
  public static extern void PolygonVector_Add(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_PolygonVector_size")]
  public static extern uint PolygonVector_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_PolygonVector_capacity")]
  public static extern uint PolygonVector_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_PolygonVector_reserve")]
  public static extern void PolygonVector_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_new_PolygonVector__SWIG_0")]
  public static extern global::System.IntPtr new_PolygonVector__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_new_PolygonVector__SWIG_1")]
  public static extern global::System.IntPtr new_PolygonVector__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_new_PolygonVector__SWIG_2")]
  public static extern global::System.IntPtr new_PolygonVector__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_PolygonVector_getitemcopy")]
  public static extern global::System.IntPtr PolygonVector_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_PolygonVector_getitem")]
  public static extern global::System.IntPtr PolygonVector_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_PolygonVector_setitem")]
  public static extern void PolygonVector_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_PolygonVector_AddRange")]
  public static extern void PolygonVector_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_PolygonVector_GetRange")]
  public static extern global::System.IntPtr PolygonVector_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_PolygonVector_Insert")]
  public static extern void PolygonVector_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_PolygonVector_InsertRange")]
  public static extern void PolygonVector_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_PolygonVector_RemoveAt")]
  public static extern void PolygonVector_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_PolygonVector_RemoveRange")]
  public static extern void PolygonVector_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_PolygonVector_Repeat")]
  public static extern global::System.IntPtr PolygonVector_Repeat(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_PolygonVector_Reverse__SWIG_0")]
  public static extern void PolygonVector_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_PolygonVector_Reverse__SWIG_1")]
  public static extern void PolygonVector_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_PolygonVector_SetRange")]
  public static extern void PolygonVector_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_delete_PolygonVector")]
  public static extern void delete_PolygonVector(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_new_RegionPtrRegionPtrPair__SWIG_0")]
  public static extern global::System.IntPtr new_RegionPtrRegionPtrPair__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_new_RegionPtrRegionPtrPair__SWIG_1")]
  public static extern global::System.IntPtr new_RegionPtrRegionPtrPair__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_new_RegionPtrRegionPtrPair__SWIG_2")]
  public static extern global::System.IntPtr new_RegionPtrRegionPtrPair__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_RegionPtrRegionPtrPair_first_set")]
  public static extern void RegionPtrRegionPtrPair_first_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_RegionPtrRegionPtrPair_first_get")]
  public static extern global::System.IntPtr RegionPtrRegionPtrPair_first_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_RegionPtrRegionPtrPair_second_set")]
  public static extern void RegionPtrRegionPtrPair_second_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_RegionPtrRegionPtrPair_second_get")]
  public static extern global::System.IntPtr RegionPtrRegionPtrPair_second_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_delete_RegionPtrRegionPtrPair")]
  public static extern void delete_RegionPtrRegionPtrPair(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport(""+importdll+"", EntryPoint="CSharp_Polygon_SWIGUpcast")]
  public static extern global::System.IntPtr Polygon_SWIGUpcast(global::System.IntPtr jarg1);
}

}
