//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace SWIG.BWTA {
 
	// defaults
	using System; 
	using System.Runtime.InteropServices; 
	// BWAPI
	using BWAPI;

public partial class RectangleArrayDouble : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal RectangleArrayDouble(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(RectangleArrayDouble obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~RectangleArrayDouble() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          bwtaPINVOKE.delete_RectangleArrayDouble(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  
public override int GetHashCode()
{
   return this.swigCPtr.Handle.GetHashCode();
}

public override bool Equals(object obj)
{
    bool equal = false;
    if (obj is RectangleArrayDouble)
      equal = (((RectangleArrayDouble)obj).swigCPtr.Handle == this.swigCPtr.Handle);
    return equal;
}
  
public bool Equals(RectangleArrayDouble obj) 
{
    if (obj == null) return false;
    return (obj.swigCPtr.Handle == this.swigCPtr.Handle);
}

public static bool operator ==(RectangleArrayDouble obj1, RectangleArrayDouble obj2)
{
    if (object.ReferenceEquals(obj1, obj2)) return true;
    if (object.ReferenceEquals(obj1, null)) return false;
    if (object.ReferenceEquals(obj2, null)) return false;
   
    return obj1.Equals(obj2);
}

public static bool operator !=(RectangleArrayDouble obj1, RectangleArrayDouble obj2)
{
    if (object.ReferenceEquals(obj1, obj2)) return false;
    if (object.ReferenceEquals(obj1, null)) return true;
    if (object.ReferenceEquals(obj2, null)) return true;

    return !obj1.Equals(obj2);
}




  public RectangleArrayDouble(uint width, uint height, SWIGTYPE_p_double data) : this(bwtaPINVOKE.new_RectangleArrayDouble__SWIG_0(width, height, SWIGTYPE_p_double.getCPtr(data)), true) {
  }

  public RectangleArrayDouble(uint width, uint height) : this(bwtaPINVOKE.new_RectangleArrayDouble__SWIG_1(width, height), true) {
  }

  public RectangleArrayDouble(uint width) : this(bwtaPINVOKE.new_RectangleArrayDouble__SWIG_2(width), true) {
  }

  public RectangleArrayDouble() : this(bwtaPINVOKE.new_RectangleArrayDouble__SWIG_3(), true) {
  }

  public RectangleArrayDouble(RectangleArrayDouble rectangleArray) : this(bwtaPINVOKE.new_RectangleArrayDouble__SWIG_4(RectangleArrayDouble.getCPtr(rectangleArray)), true) {
    if (bwtaPINVOKE.SWIGPendingException.Pending) throw bwtaPINVOKE.SWIGPendingException.Retrieve();
  }

  public uint getWidth() {
    uint ret = bwtaPINVOKE.RectangleArrayDouble_getWidth(swigCPtr);
    return ret;
  }

  public uint getHeight() {
    uint ret = bwtaPINVOKE.RectangleArrayDouble_getHeight(swigCPtr);
    return ret;
  }

  public double getItem(uint x, uint y) {
    double ret = bwtaPINVOKE.RectangleArrayDouble_getItem(swigCPtr, x, y);
    return ret;
  }

  public double getItemSafe(uint x, uint y) {
    double ret = bwtaPINVOKE.RectangleArrayDouble_getItemSafe(swigCPtr, x, y);
    return ret;
  }

  public void setItem(uint x, uint y, SWIGTYPE_p_double item) {
    bwtaPINVOKE.RectangleArrayDouble_setItem(swigCPtr, x, y, SWIGTYPE_p_double.getCPtr(item));
  }

  public void resize(uint width, uint height) {
    bwtaPINVOKE.RectangleArrayDouble_resize(swigCPtr, width, height);
  }

  public void printToFile(SWIGTYPE_p_FILE f) {
    bwtaPINVOKE.RectangleArrayDouble_printToFile(swigCPtr, SWIGTYPE_p_FILE.getCPtr(f));
  }

  public void saveToFile(string fileName) {
    bwtaPINVOKE.RectangleArrayDouble_saveToFile(swigCPtr, fileName);
    if (bwtaPINVOKE.SWIGPendingException.Pending) throw bwtaPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setTo(double value) {
    bwtaPINVOKE.RectangleArrayDouble_setTo(swigCPtr, value);
  }

  public void setBorderTo(double value) {
    bwtaPINVOKE.RectangleArrayDouble_setBorderTo(swigCPtr, value);
  }

}

}
