//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace SWIG.BWTA {
 
	// defaults
	using System; 
	using System.Runtime.InteropServices; 
	// BWAPI
	using BWAPI;

public partial class Region : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Region(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Region obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Region() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          bwtaPINVOKE.delete_Region(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  
public override int GetHashCode()
{
   return this.swigCPtr.Handle.GetHashCode();
}

public override bool Equals(object obj)
{
    bool equal = false;
    if (obj is Region)
      equal = (((Region)obj).swigCPtr.Handle == this.swigCPtr.Handle);
    return equal;
}
  
public bool Equals(Region obj) 
{
    if (obj == null) return false;
    return (obj.swigCPtr.Handle == this.swigCPtr.Handle);
}

public static bool operator ==(Region obj1, Region obj2)
{
    if (object.ReferenceEquals(obj1, obj2)) return true;
    if (object.ReferenceEquals(obj1, null)) return false;
    if (object.ReferenceEquals(obj2, null)) return false;
   
    return obj1.Equals(obj2);
}

public static bool operator !=(Region obj1, Region obj2)
{
    if (object.ReferenceEquals(obj1, obj2)) return false;
    if (object.ReferenceEquals(obj1, null)) return true;
    if (object.ReferenceEquals(obj2, null)) return true;

    return !obj1.Equals(obj2);
}




  public virtual Polygon getPolygon() {
    Polygon ret = new Polygon(bwtaPINVOKE.Region_getPolygon(swigCPtr), false);
    return ret;
  }

  public virtual Position getCenter() {
    Position ret = new Position(bwtaPINVOKE.Region_getCenter(swigCPtr), false);
    return ret;
  }

  public virtual ChokepointPtrSet getChokepoints() {
    ChokepointPtrSet ret = new ChokepointPtrSet(bwtaPINVOKE.Region_getChokepoints(swigCPtr), false);
    return ret;
  }

  public virtual BaseLocationPtrSet getBaseLocations() {
    BaseLocationPtrSet ret = new BaseLocationPtrSet(bwtaPINVOKE.Region_getBaseLocations(swigCPtr), false);
    return ret;
  }

  public virtual bool isReachable(Region region) {
    bool ret = bwtaPINVOKE.Region_isReachable(swigCPtr, Region.getCPtr(region));
    return ret;
  }

  public virtual RegionPtrSet getReachableRegions() {
    RegionPtrSet ret = new RegionPtrSet(bwtaPINVOKE.Region_getReachableRegions(swigCPtr), false);
    return ret;
  }

}

}
