//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace SWIG.BWAPI {

public partial class ForcePtrSet : global::System.IDisposable 
#if !SWIG_DOTNET_3
    , global::System.Collections.Generic.ICollection<Force>
#endif
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ForcePtrSet(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ForcePtrSet obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ForcePtrSet() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          bwapiPINVOKE.delete_ForcePtrSet(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }


  
  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsReadOnly {
    get { 
      return false; 
    }
  }

#if !SWIG_DOTNET_1
 public System.Collections.Generic.ICollection<Force> Values {
    get {
      System.Collections.Generic.ICollection<Force> values = new System.Collections.Generic.List<Force>();
      global::System.IntPtr iter = create_iterator_begin();
      try {
        while (true) {
          values.Add(get_next_key(iter));
        }
      } catch (global::System.ArgumentOutOfRangeException) {
      }
      return values;
    }
  }
 
  public bool Contains(Force item) {
    if ( ContainsKey(item)) {
      return true;
    } else {
      return false;
    }
  }

  public void CopyTo(Force[] array) {
    CopyTo(array, 0);
  }

  public void CopyTo( Force[] array, int arrayIndex) {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (arrayIndex+this.Count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");

   System.Collections.Generic.IList<Force> keyList = new System.Collections.Generic.List<Force>(this.Values);
    for (int i = 0; i < this.Count; i++) {
      Force currentKey = keyList[i];
      array.SetValue( currentKey, arrayIndex+i);
    }
  }

  System.Collections.Generic.IEnumerator< Force> System.Collections.Generic.IEnumerable<Force>.GetEnumerator() {
    return new ForcePtrSetEnumerator(this);
  }

  System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() {
    return new ForcePtrSetEnumerator(this);
  }

  public ForcePtrSetEnumerator GetEnumerator() {
    return new ForcePtrSetEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class ForcePtrSetEnumerator : System.Collections.IEnumerator, 
      System.Collections.Generic.IEnumerator< Force>
  {
    private ForcePtrSet collectionRef;
    private System.Collections.Generic.IList<Force> keyCollection;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public ForcePtrSetEnumerator(ForcePtrSet collection) {
      collectionRef = collection;
      keyCollection = new System.Collections.Generic.List<Force>(collection.Values);
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public  Force Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return ( Force)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        Force currentKey = keyCollection[currentIndex];
        currentObject = currentKey;
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
      currentIndex = -1;
      currentObject = null;
    }
  }
#endif
  

  public ForcePtrSet() : this(bwapiPINVOKE.new_ForcePtrSet__SWIG_0(), true) {
  }

  public ForcePtrSet(ForcePtrSet other) : this(bwapiPINVOKE.new_ForcePtrSet__SWIG_1(ForcePtrSet.getCPtr(other)), true) {
    if (bwapiPINVOKE.SWIGPendingException.Pending) throw bwapiPINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = bwapiPINVOKE.ForcePtrSet_size(swigCPtr);
    return ret;
  }

  public bool empty() {
    bool ret = bwapiPINVOKE.ForcePtrSet_empty(swigCPtr);
    return ret;
  }

  public void Clear() {
    bwapiPINVOKE.ForcePtrSet_Clear(swigCPtr);
  }

  public Force getitem(Force key) {
    global::System.IntPtr cPtr = bwapiPINVOKE.ForcePtrSet_getitem(swigCPtr, Force.getCPtr(key));
    Force ret = (cPtr == global::System.IntPtr.Zero) ? null : new Force(cPtr, false);
    if (bwapiPINVOKE.SWIGPendingException.Pending) throw bwapiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool ContainsKey(Force key) {
    bool ret = bwapiPINVOKE.ForcePtrSet_ContainsKey(swigCPtr, Force.getCPtr(key));
    return ret;
  }

  public void Add(Force key) {
    bwapiPINVOKE.ForcePtrSet_Add(swigCPtr, Force.getCPtr(key));
    if (bwapiPINVOKE.SWIGPendingException.Pending) throw bwapiPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool Remove(Force key) {
    bool ret = bwapiPINVOKE.ForcePtrSet_Remove(swigCPtr, Force.getCPtr(key));
    return ret;
  }

  public global::System.IntPtr create_iterator_begin() {
    global::System.IntPtr ret = bwapiPINVOKE.ForcePtrSet_create_iterator_begin(swigCPtr);
    return ret;
  }

  public Force get_next_key(global::System.IntPtr swigiterator) {
    global::System.IntPtr cPtr = bwapiPINVOKE.ForcePtrSet_get_next_key(swigCPtr, swigiterator);
    Force ret = (cPtr == global::System.IntPtr.Zero) ? null : new Force(cPtr, false);
    if (bwapiPINVOKE.SWIGPendingException.Pending) throw bwapiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
