//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace SWIG.BWAPI {

public partial class Race : Type {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal Race(global::System.IntPtr cPtr, bool cMemoryOwn) : base(bwapiPINVOKE.Race_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Race obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Race() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          bwapiPINVOKE.delete_Race(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  
public override int GetHashCode()
{
   return this.swigCPtr.Handle.GetHashCode();
}

public override bool Equals(object obj)
{
    bool equal = false;
    if (obj is Race)
      equal = (((Race)obj).swigCPtr.Handle == this.swigCPtr.Handle);
    return equal;
}
  
public bool Equals(Race obj) 
{
    if (obj == null) return false;
    return (obj.swigCPtr.Handle == this.swigCPtr.Handle);
}

public static bool operator ==(Race obj1, Race obj2)
{
    if (object.ReferenceEquals(obj1, obj2)) return true;
    if (object.ReferenceEquals(obj1, null)) return false;
    if (object.ReferenceEquals(obj2, null)) return false;
   
    return obj1.Equals(obj2);
}

public static bool operator !=(Race obj1, Race obj2)
{
    if (object.ReferenceEquals(obj1, obj2)) return false;
    if (object.ReferenceEquals(obj1, null)) return true;
    if (object.ReferenceEquals(obj2, null)) return true;

    return !obj1.Equals(obj2);
}




  public Race() : this(bwapiPINVOKE.new_Race__SWIG_0(), true) {
  }

  public Race(int id) : this(bwapiPINVOKE.new_Race__SWIG_1(id), true) {
  }

  public string getName() {
    string ret = bwapiPINVOKE.Race_getName(swigCPtr);
    return ret;
  }

  public string c_str() {
    string ret = bwapiPINVOKE.Race_c_str(swigCPtr);
    return ret;
  }

  public UnitType getWorker() {
    UnitType ret = new UnitType(bwapiPINVOKE.Race_getWorker(swigCPtr), true);
    return ret;
  }

  public UnitType getCenter() {
    UnitType ret = new UnitType(bwapiPINVOKE.Race_getCenter(swigCPtr), true);
    return ret;
  }

  public UnitType getRefinery() {
    UnitType ret = new UnitType(bwapiPINVOKE.Race_getRefinery(swigCPtr), true);
    return ret;
  }

  public UnitType getTransport() {
    UnitType ret = new UnitType(bwapiPINVOKE.Race_getTransport(swigCPtr), true);
    return ret;
  }

  public UnitType getSupplyProvider() {
    UnitType ret = new UnitType(bwapiPINVOKE.Race_getSupplyProvider(swigCPtr), true);
    return ret;
  }

}

}
