//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace SWIG.BWAPI {

public partial class TilePositionDoublePair : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TilePositionDoublePair(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TilePositionDoublePair obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~TilePositionDoublePair() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          bwapiPINVOKE.delete_TilePositionDoublePair(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  
public override int GetHashCode()
{
   return this.swigCPtr.Handle.GetHashCode();
}

public override bool Equals(object obj)
{
    bool equal = false;
    if (obj is TilePositionDoublePair)
      equal = (((TilePositionDoublePair)obj).swigCPtr.Handle == this.swigCPtr.Handle);
    return equal;
}
  
public bool Equals(TilePositionDoublePair obj) 
{
    if (obj == null) return false;
    return (obj.swigCPtr.Handle == this.swigCPtr.Handle);
}

public static bool operator ==(TilePositionDoublePair obj1, TilePositionDoublePair obj2)
{
    if (object.ReferenceEquals(obj1, obj2)) return true;
    if (object.ReferenceEquals(obj1, null)) return false;
    if (object.ReferenceEquals(obj2, null)) return false;
   
    return obj1.Equals(obj2);
}

public static bool operator !=(TilePositionDoublePair obj1, TilePositionDoublePair obj2)
{
    if (object.ReferenceEquals(obj1, obj2)) return false;
    if (object.ReferenceEquals(obj1, null)) return true;
    if (object.ReferenceEquals(obj2, null)) return true;

    return !obj1.Equals(obj2);
}




  public TilePositionDoublePair() : this(bwapiPINVOKE.new_TilePositionDoublePair__SWIG_0(), true) {
  }

  public TilePositionDoublePair(TilePosition t, double u) : this(bwapiPINVOKE.new_TilePositionDoublePair__SWIG_1(TilePosition.getCPtr(t), u), true) {
    if (bwapiPINVOKE.SWIGPendingException.Pending) throw bwapiPINVOKE.SWIGPendingException.Retrieve();
  }

  public TilePositionDoublePair(TilePositionDoublePair p) : this(bwapiPINVOKE.new_TilePositionDoublePair__SWIG_2(TilePositionDoublePair.getCPtr(p)), true) {
    if (bwapiPINVOKE.SWIGPendingException.Pending) throw bwapiPINVOKE.SWIGPendingException.Retrieve();
  }

  public TilePosition first {
    set {
      bwapiPINVOKE.TilePositionDoublePair_first_set(swigCPtr, TilePosition.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = bwapiPINVOKE.TilePositionDoublePair_first_get(swigCPtr);
      TilePosition ret = (cPtr == global::System.IntPtr.Zero) ? null : new TilePosition(cPtr, false);
      return ret;
    } 
  }

  public double second {
    set {
      bwapiPINVOKE.TilePositionDoublePair_second_set(swigCPtr, value);
    } 
    get {
      double ret = bwapiPINVOKE.TilePositionDoublePair_second_get(swigCPtr);
      return ret;
    } 
  }

}

}
